defaults:
   - _self_
   - dataset: cityscapes

name: PSPNet
n_gpu: 1
use_synch_bn: False
crop_size: 512
mean: [0.28689529, 0.32513294, 0.28389176]
std: [0.17613647, 0.18099176, 0.17772235]
threshold_value: 0.8

train_transforms:
  - _target_: albumentations.SmallestMaxSize
    max_size: ${crop_size}
  - _target_: albumentations.RandomCrop
    height: ${crop_size}
    width: ${crop_size}
  - _target_: albumentations.AdvancedBlur
    p: 0.75
  - _target_: albumentations.GaussNoise
    p: 0.75
  - _target_: albumentations.HorizontalFlip
    p: 0.5
  - _target_: albumentations.CLAHE
    p: 0.75
  - _target_: albumentations.RandomBrightnessContrast
    p: 0.75
  - _target_: albumentations.RandomGamma
    p: 0.75
  - _target_: albumentations.ColorJitter
    p: 0.75
  - _target_: albumentations.Normalize
    mean: ${mean}
    std: ${std}
  - _target_: albumentations.pytorch.ToTensorV2
    transpose_mask: True

val_transforms:
  - _target_: albumentations.SmallestMaxSize
    max_size: ${crop_size}
  - _target_: albumentations.RandomCrop
    height: ${crop_size}
    width: ${crop_size}
  - _target_: albumentations.Normalize
    mean: ${mean}
    std: ${std}
  - _target_: albumentations.pytorch.ToTensorV2
    transpose_mask: True

train_loader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: src.dataloaders.CityscapesDataset
    root: ${dataset.data_dir}
    split: train
    transforms:
      _target_: albumentations.Compose
      transforms: ${train_transforms}
    id_to_train_id: ${dataset.id_to_train_id}
    load_limit: 8
  shuffle: True
  batch_size: 4
  num_workers: 2

val_loader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: src.dataloaders.CityscapesDataset
    root: ${dataset.data_dir}
    split: val
    transforms:
      _target_: albumentations.Compose
      transforms: ${val_transforms}
    id_to_train_id: ${dataset.id_to_train_id}
    load_limit: 8
  batch_size: 4
  num_workers: 2

accelerator:
  _target_: accelerate.Accelerator
  cpu: False
#  mixed_precision: fp16

#model:
#  _target_: src.models.PSPNet
#  backbone_name: resnet101
#  freeze_bn: False
#  freeze_backbone: False

model:
  _target_: src.models.UNet
  backbone_name: resnet50

differential_lr: True

#loss:
#  _target_: src.utils.DiceCrossEntropyLoss
#  weight: 0.15

loss:
  _target_: src.utils.losses.BCEDiceBoundaryLoss
  is_3d: False

metric:
  _target_: src.utils.PixAccIoUMetric
  reduction: macro
  threshold_value: ${threshold_value}

#optimizer:
#  _target_: torch.optim.SGD
#  lr: 0.01
#  weight_decay: 1e-4
#  momentum: 0.9

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-4
  eps: 1e-08

visualizer:
  _target_: src.utils.Visualization
  palette: ${dataset.palette}
  mean: ${mean}
  std: ${std}
  threshold_value: ${threshold_value}

trainer:
  epochs: 100
  save_dir: saved\
  save_period: 5
  monitor: max mIoU
#  early_stop: 10
  tensorboard: True
  log_dir: saved/runs
  log_per_iter: 20
  val: True
  val_per_epochs: 2

resume:
