data_dir: C:\Documents\Datasets\CityScapes

palette: [[128, 64, 128], [244, 35, 232], [0, 0, 0]]

ignore_label: 3
id_to_train_id:
  -1: ${..ignore_label}
  0: ${..ignore_label}
  1: ${..ignore_label}
  2: ${..ignore_label}
  3: ${..ignore_label}
  4: ${..ignore_label}
  5: ${..ignore_label}
  6: ${..ignore_label}
  7: ${..ignore_label}
  8: ${..ignore_label}
  9: ${..ignore_label}
  10: ${..ignore_label}
  11: ${..ignore_label}
  12: ${..ignore_label}
  13: ${..ignore_label}
  14: ${..ignore_label}
  15: ${..ignore_label}
  16: ${..ignore_label}
  17: ${..ignore_label}
  18: ${..ignore_label}
  19: ${..ignore_label}
  20: ${..ignore_label}
  21: ${..ignore_label}
  22: ${..ignore_label}
  23: ${..ignore_label}
  24: 1
  25: 2
  26: ${..ignore_label}
  27: ${..ignore_label}
  28: ${..ignore_label}
  29: ${..ignore_label}
  30: ${..ignore_label}
  31: ${..ignore_label}
  32: ${..ignore_label}
  33: ${..ignore_label}
